import type { FounderProfile } from './founder-card.types'

/** Real-feeling, diverse student founders. GreenStack ties into the existing
 *  landing news ("GreenStack Raises Pre-Seed"). No tiers, no trust scores. */
export const founderCards: FounderProfile[] = [
  {
    id: 'aysel',
    name: 'Aysel Məmmədova',
    role: 'Founder & CEO',
    startup: 'GreenStack',
    university: 'Baku State University',
    program: 'Computer Science · 3rd year',
    building: 'Climate-tech app that tracks and reduces campus energy use across university buildings.',
    stage: 'mvp',
    skills: ['React', 'Sustainability', 'Product'],
    lookingFor: 'a technical co-founder',
    traction: 'Piloting at 2 faculties',
    portrait: {
      src: 'images/founders/aysel-mammadova.webp',
      alt: 'Illustrative editorial portrait of Aysel Məmmədova',
      position: '50% 38%',
    },
    accent: 'emerald',
    founderStory: 'Aysel began by comparing energy waste across lecture buildings and discovered that campus teams had data, but no simple way to act on it.',
    mission: 'Help universities turn everyday energy data into measurable reductions that students and facilities teams can understand together.',
    currentFocus: 'Converting two faculty pilots into a repeatable campus-wide deployment and strengthening the technical founding team.',
    progress: 'Live pilot across two faculties with weekly energy-use reviews and an expanding set of building-level insights.',
    profileHref: '/sign-up',
  },
  {
    id: 'reshad',
    name: 'Rəşad Quliyev',
    role: 'Founder',
    startup: 'EduFlow',
    university: 'ADA University',
    program: 'Information Tech · 2nd year',
    building: 'AI study companion that turns lecture recordings into adaptive practice questions.',
    stage: 'validation',
    skills: ['Python', 'ML', 'Pedagogy'],
    lookingFor: 'a product designer',
    traction: '340 student sign-ups',
    portrait: {
      src: 'images/founders/reshad-quliyev.webp',
      alt: 'Illustrative editorial portrait of Rəşad Quliyev',
      position: '50% 35%',
    },
    accent: 'blue',
    founderStory: 'Rəşad built the first EduFlow prototype after watching classmates repeatedly pause long recordings without knowing what to practise next.',
    mission: 'Transform passive lecture content into focused, adaptive practice that helps students discover where their understanding is weakest.',
    currentFocus: 'Improving question quality, mapping the complete learner journey, and finding a product designer for the next validation cycle.',
    progress: 'The early release has attracted 340 student sign-ups and is collecting structured feedback from active learners.',
    profileHref: '/sign-up',
  },
  {
    id: 'leyla',
    name: 'Leyla Əliyeva',
    role: 'Founder & CEO',
    startup: 'MediMatch',
    university: 'UNEC',
    program: 'Business · Final year',
    building: 'Marketplace connecting students with affordable verified medical professionals.',
    stage: 'revenue',
    skills: ['Operations', 'Health', 'Strategy'],
    lookingFor: 'seed investment',
    traction: '$2.1k MRR · 18 providers',
    portrait: {
      src: 'images/founders/leyla-aliyeva.webp',
      alt: 'Illustrative editorial portrait of Leyla Əliyeva',
      position: '50% 36%',
    },
    accent: 'gold',
    founderStory: 'Leyla saw students postpone essential appointments because trusted and affordable care was fragmented across informal recommendations.',
    mission: 'Make verified medical support easier to compare and access while giving responsible providers a clearer path to student communities.',
    currentFocus: 'Strengthening provider operations, improving repeat bookings, and preparing the evidence required for a disciplined seed round.',
    progress: 'Eighteen verified providers now generate $2.1k in monthly recurring revenue across the initial marketplace.',
    profileHref: '/sign-up',
  },
]
