import type { FounderProfile } from './founder-card.types'

/** Illustrative profiles for interaction tests. They are not customer or traction claims. */
export const founderCards: FounderProfile[] = [
  {
    id: 'aysel',
    name: 'Aysel Məmmədova',
    role: 'Founder & CEO',
    startup: 'GreenStack',
    university: 'Baku State University',
    program: 'Computer Science · 3rd year',
    building: 'Climate-tech app that tracks and reduces campus energy use across university buildings.',
    stage: 'mvp',
    skills: ['React', 'Sustainability', 'Product'],
    metrics: [
      { value: 'Sample', label: 'Pilot record', icon: 'pilot' },
      { value: 'Defined', label: 'Campus scope', icon: 'campus' },
      { value: 'Pending', label: 'Impact review', icon: 'impact' },
    ],
    lookingFor: { eyebrow: 'Looking for a', title: 'Technical Co-founder', icon: 'code' },
    tractionBadge: 'Illustrative pilot profile',
    portrait: {
      src: 'images/founders/aysel-mammadova.webp',
      alt: 'Illustrative editorial portrait of Aysel Məmmədova',
      position: '50% 38%',
    },
    accent: 'emerald',
    founderStory: 'Aysel began by comparing energy waste across lecture buildings and discovered that campus teams had data, but no simple way to act on it.',
    mission: 'Help universities turn everyday energy data into measurable reductions that students and facilities teams can understand together.',
    currentFocus: 'Converting two faculty pilots into a repeatable campus-wide deployment and strengthening the technical founding team.',
    progress: 'The demo record shows how a team could connect a campus pilot to evidence and weekly operating reviews.',
    profileHref: '/sign-up',
  },
  {
    id: 'reshad',
    name: 'Rəşad Quliyev',
    role: 'Founder',
    startup: 'EduFlow',
    university: 'ADA University',
    program: 'Information Tech · 2nd year',
    building: 'AI study companion that turns lecture recordings into adaptive practice questions.',
    stage: 'validation',
    skills: ['Python', 'ML', 'Pedagogy'],
    metrics: [
      { value: 'Sample', label: 'User record', icon: 'users' },
      { value: 'Pending', label: 'Usage review', icon: 'activity' },
      { value: 'Demo', label: 'Feedback', icon: 'rating' },
    ],
    lookingFor: { eyebrow: 'Looking for a', title: 'Product Designer', icon: 'design' },
    tractionBadge: 'Illustrative validation profile',
    portrait: {
      src: 'images/founders/reshad-quliyev.webp',
      alt: 'Illustrative editorial portrait of Rəşad Quliyev',
      position: '50% 35%',
    },
    accent: 'blue',
    founderStory: 'Rəşad built the first EduFlow prototype after watching classmates repeatedly pause long recordings without knowing what to practise next.',
    mission: 'Transform passive lecture content into focused, adaptive practice that helps students discover where their understanding is weakest.',
    currentFocus: 'Improving question quality, mapping the complete learner journey, and finding a product designer for the next validation cycle.',
    progress: 'The demo record shows a validation cycle with structured feedback from illustrative learners.',
    profileHref: '/sign-up',
  },
  {
    id: 'leyla',
    name: 'Leyla Əliyeva',
    role: 'Founder & CEO',
    startup: 'MediMatch',
    university: 'UNEC',
    program: 'Business · Final year',
    building: 'Marketplace connecting students with affordable verified medical professionals.',
    stage: 'revenue',
    skills: ['Operations', 'Health', 'Strategy'],
    metrics: [
      { value: 'Sample', label: 'Revenue record', icon: 'revenue' },
      { value: 'Pending', label: 'Provider review', icon: 'providers' },
      { value: 'Demo', label: 'Repeat signal', icon: 'growth' },
    ],
    lookingFor: { eyebrow: 'Looking for', title: 'Seed Investment', icon: 'funding' },
    tractionBadge: 'Illustrative operating profile',
    portrait: {
      src: 'images/founders/leyla-aliyeva.webp',
      alt: 'Illustrative editorial portrait of Leyla Əliyeva',
      position: '50% 36%',
    },
    accent: 'gold',
    founderStory: 'Leyla saw students postpone essential appointments because trusted and affordable care was fragmented across informal recommendations.',
    mission: 'Make verified medical support easier to compare and access while giving responsible providers a clearer path to student communities.',
    currentFocus: 'Strengthening provider operations, improving repeat bookings, and preparing the evidence required for a disciplined seed round.',
    progress: 'The demo record illustrates how provider, revenue and repeat-use evidence could be reviewed without claiming real traction.',
    profileHref: '/sign-up',
  },
]
